import { MapProps } from '@/components/Map'
import HomeTemplate from '@/components/templates/Home'
import client from 'graphql/client'
import { GetPlacesQuery } from 'graphql/generated/graphql'
import { GET_PLACES } from 'graphql/queries'
import type { GetStaticProps } from 'next'
import Head from 'next/head'

const Home = ({ places }: MapProps) => {
  return (
    <>
      <Head>
        <title>Home - Store App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <HomeTemplate places={places} />
    </>
  )
}
export const getStaticProps: GetStaticProps = async () => {
  const { places } = await client.request<GetPlacesQuery>(GET_PLACES)

  return {
    props: { places }
  }
}

export default Home
